require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,bundle,setup}'
    - !ruby/regexp /old_and_unused\.rb$/

Style/Documentation:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 4
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/FilePath:
  SpecSuffixOnly: true
RSpec/NestedGroups:
  Enabled: false
