require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake,bundle,setup}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'vendor/**/*'
    - 'vendor/'
    - 'app/helpers/components/*'

Style/Documentation:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 4
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
