# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActionablePromotionMailer`.
# Please instead update this file by running `bin/tapioca dsl ActionablePromotionMailer`.


class ActionablePromotionMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def notify; end
  end
end
