# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RegistrationMailer`.
# Please instead update this file by running `bin/tapioca dsl RegistrationMailer`.


class RegistrationMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def welcome_email; end
  end
end
