# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `TimeSensitiveMailer`.
# Please instead update this file by running `bin/tapioca dsl TimeSensitiveMailer`.


class TimeSensitiveMailer
  class << self
    sig { returns(::ActionMailer::MessageDelivery) }
    def notify; end
  end
end
