wiki_query: https://en.wikipedia.org/w/api.php?
wiki_base_params:
  action: parse
  prop: text
  format: json

mls:
  wiki_specific_params:
    page: Major_League_Soccer
    section: 9
  sport_api:
    url: https://stats-api.mlssoccer.com/competitions/MLS-COM-000001/seasons/MLS-SEA-0001K9/standings?is_live=true
    data_path:
    - tables
    - 0
    - entries
    abbrev_path:
    - team_three_letter_code
    full_name_path:
    - team
    additional_params:
      seasonId: null
  options:
    excluded_wiki_columns:
    - eastern
    - western

nhl:
  wiki_specific_params:
    page: National_Hockey_League
    section: 9
  sport_api:
    url: https://api-web.nhle.com/v1/standings/now
    data_path:
    - standings
    abbrev_path:
    - teamAbbrev
    - default
    full_name_path:
    - teamName
    - default
  options:
    excluded_wiki_columns:
    - eastern
    - western
    - pacific
    - central
    - metropolitan
    - atlantic

# future wiki pages to seed from
# National_Basketball_Association
# National_Football_League
# Major_League_Baseball
