name: GitHub Actions Rubocop
run-name: rubocop
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  GitHub-Actions-Rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
          with:
            bundler-cache: true
      - name: bundle
        run: bundle install
      - run: bundle exec rake
      - name: rubocop
        run: bundle exec rubocop
      - name: rspec
        run: bundle exec rspec
